### ISSUE TITLE
calico doesn't install properly 

### ISSUE THREAD

**Issue by timothyclin** [PacktPublishing/Kubernetes---An-Enterprise-Guide-2E#10] opened 2022-05-06 11:15 UTC
with the latest kind, calico no longer installs with the supplied sample yaml file in chapter2: 

❯ kind version
kind v0.12.0 go1.17.8 darwin/arm64
❯ kubectl create -f calico.yaml
configmap/calico-config created
clusterrole.rbac.authorization.k8s.io/calico-kube-controllers created
clusterrolebinding.rbac.authorization.k8s.io/calico-kube-controllers created
clusterrole.rbac.authorization.k8s.io/calico-node created
clusterrolebinding.rbac.authorization.k8s.io/calico-node created
Warning: spec.template.spec.nodeSelector[beta.kubernetes.io/os]: deprecated since v1.14; use "kubernetes.io/os" instead
Warning: spec.template.metadata.annotations[scheduler.alpha.kubernetes.io/critical-pod]: non-functional in v1.16+; use the "priorityClassName" field instead
daemonset.apps/calico-node created
serviceaccount/calico-node created
deployment.apps/calico-kube-controllers created
serviceaccount/calico-kube-controllers created
unable to recognize "calico.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "calico.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "calico.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "calico.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "calico.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "calico.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "calico.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "calico.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "calico.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "calico.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "calico.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "calico.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "calico.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "calico.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
❯ kubectl get pods -A
NAMESPACE            NAME                                              READY   STATUS              RESTARTS      AGE
kube-system          calico-kube-controllers-74cd595f4b-lt6tp          0/1     ContainerCreating   0             77s
kube-system          calico-node-mjzng                                 0/1     CrashLoopBackOff    3 (34s ago)   77s
kube-system          calico-node-v9fhv                                 0/1     CrashLoopBackOff    3 (17s ago)   77s
kube-system          coredns-64897985d-4bcj7                           0/1     ContainerCreating   0             11m
kube-system          coredns-64897985d-vb9ck                           0/1     ContainerCreating   0             11m
kube-system          etcd-cluster01-control-plane                      1/1     Running             0             11m
kube-system          kube-apiserver-cluster01-control-plane            1/1     Running             0             11m
kube-system          kube-controller-manager-cluster01-control-plane   1/1     Running             0             11m
kube-system          kube-proxy-44q4b                                  1/1     Running             0             10m
kube-system          kube-proxy-z9bvn                                  1/1     Running             0             11m
kube-system          kube-scheduler-cluster01-control-plane            1/1     Running             0             11m

**Comment by timothyclin** [comment] 2022-05-06 11:25
oops - realized i didn't install the operator first. 
Once I did the operator install, it seems to work, although it still complains about apiversion of CustomResourceDefinition:
unable to recognize "calico.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"

**Comment by ssurovich** [comment] 2022-06-02 00:40
Hey @timothyclin - Sorry for the delay, I havent had a chance to check the issues as much as I would like to.  Are you still having issues with Calico?   I will check the deployment tomorrow, but I did a sanity check a few weeks go to test the scripts and it was all working, but you never know...

**Comment by ssurovich** [comment] 2022-06-02 00:57
I had a few minutes to test the scripts and they appear to work.  I did notice that your KinD version is 0.12 and the scripts assume you are running 0.11 - 0.12 jumps the K8s version to 1.23.4,  while KinD 0.11 deploys K8s 1.21.1.

The scripts works as expected using a K8s 1.21.x - Can you try using the KinD version we used in the book, 0.11 which will deploy a K8s 1.21.1 cluster?   You could also use the 0.12 version and tell KinD to deploy a 1.21.1 cluster - It might be easier to use the scripts we incude to download KinD, which will download version 0.11.

**Comment by ssurovich** [comment] 2022-06-14 13:32
Closing since it has been tested and confirmed to work when using the correct K8s/KinD version.

**Closed as completed by ssurovich** 2022-06-14 13:32 UTC
